nvbach91/4IZ268-2021-2022-ZS

www/maka09/hw08/index.html, www/maka09/hw08/main.js
odevzdávám dú číslo 8 https://eso.vse.cz/~maka09/cv08/
=> maka09-hw08

www/matj27/hw08/homework.js, www/matj27/hw08/index.html
Dobrý večer, odevzdávám dů08.
Matějka
https://eso.vse.cz/~matj27/hw08/
https://eso.vse.cz/~matj27/hw08/index.html
https://eso.vse.cz/~matj27/hw08/homework.js
=> matj27-hw08

www/homework.js, www/index.html, www/stom19.hw8/homework.js, www/stom19.hw8/index.html
posilam nahrany domaci ukol na server:  https://eso.vse.cz/~stom19/cv8/
=> stom19-hw8

www/legv02/hw08/homework.js, www/legv02/hw08/index.html
Odevzdávám úkol hw08:
https://eso.vse.cz/~legv02/hw08/
Vojtěch Legler (legv02)
=> legv02-hw08

www/vanv08/hw08/homework.js, www/vanv08/hw08/index.html
Domaci ukol hw08
[https://eso.vse.cz/~vanv08/hw08/](https://eso.vse.cz/~vanv08/hw08/)
=> vanv08-hw08

www/muso00/hw08/homework.js, www/muso00/hw08/index.html
Odevzdávám úkol č.8 https://eso.vse.cz/~muso00/cv08/
=> muso00-hw08

www/rolt01/hw08/homework.js, www/rolt01/hw08/index.html
Odevzdávám domácí úkol: https://eso.vse.cz/~rolt01/cv08x/
=> rolt01-hw08

www/sirm02/hw08/homework.js, www/sirm02/hw08/index.html
Odevzdávám úkol č.8  [https://eso.vse.cz/~sirm02/cv08/](https://eso.vse.cz/~sirm02/cv08/)
=> sirm02-hw08

www/ploa00/hw08/homework.js, www/ploa00/hw08/index.html
Odevzdávám du č. 8 https://eso.vse.cz/~ploa00/du08/
=> ploa00-hw08

www/vitl03/cv08/index.html, www/vitl03/cv08/main.js
Dobrý den,
odevzdávám domácí úkol ze cv 8.
Odkaz: [eso.vse.cz](https://eso.vse.cz/~vitl03/cv08/)
Díky,
vitl03, Lukáš Vít
=> vitl03-hw08

www/orad01/hw08/homework.js, www/orad01/hw08/index.html
Odevzdávám domácí úkol č.8    https://eso.vse.cz/~orad01/hw08/
=> orad01-hw08

www/urvo00/hw08/homework.js, www/urvo00/hw08/index.html
Dobrý den, odevzdávám úkol č. 8:
[https://eso.vse.cz/~urvo00/cv08/](https://eso.vse.cz/~urvo00/cv08/)
=> urvo00-hw08

www/sesm00/hw08/app.js, www/sesm00/hw08/index.html
Odevzdávám domácí úkol č.8 [https://eso.vse.cz/~sesm00/cv08/](https://eso.vse.cz/~sesm00/cv08/)
=> sesm00-HW08

www/slaj26/hw08/homework.js, www/slaj26/hw08/index.html
Odevzdávám úkol 8.
https://eso.vse.cz/~slaj26/cv08/
=> slaj26-hw08

www/kouj10/hw08/cv08/index.html, www/kouj10/hw08/cv08/main.js, www/kouj10/hw08/index.html, www/kouj10/hw08/main.js
Odevzdávám domácí úkol číslo 8: [https://eso.vse.cz/~kouj10/cv08/](https://eso.vse.cz/~kouj10/cv08/).
=> kouj10-hw08

www/nejj02/hw08/homework.js, www/nejj02/hw08/index.html
Dobrý večer,
odevzdávám domácí úkol č. 8:
https://eso.vse.cz/~nejj02/hw08/
S pozdravem
Jan Nejedlý
=> nejj02-hw08

www/jocv00/hw08/index.html, www/jocv00/hw08/main.js
Odevzdávám domácí úkol č.8:
https://eso.vse.cz/~jocv00/cv08/homework/
=> jocv00-hw08

www/immm00/hw08/homework.js, www/immm00/hw08/index.html
Odevzdávám domácí úkol č.8
https://eso.vse.cz/~immm00/cv08/
=> immm00-hw08

www/getj00/hw08/homework.js, www/getj00/hw08/index.html
Odevzdávám 1. úkol z JavaScriptu, dokud je to ještě lehké.
[https://eso.vse.cz/~getj00/hw08/](https://eso.vse.cz/~getj00/hw08/)
[https://eso.vse.cz/~getj00/hw08/index.html](https://eso.vse.cz/~getj00/hw08/index.html)
[https://eso.vse.cz/~getj00/hw08/homework.js](https://eso.vse.cz/~getj00/hw08/homework.js)
=> getj00-hw08

www/sotv02/hw08/homework.js, www/sotv02/hw08/index.html
Odevzdávám domácí úkol č.8 [https://eso.vse.cz/~sotv02/cv08/](https://eso.vse.cz/~sotv02/cv08/)
=> sotv02-hw08

www/bukp00/hw08/homework.js, www/bukp00/hw08/index.html
Odevzdávám úkol cv08: https://eso.vse.cz/~bukp00/cv08/
=> bukp00-hw08

www/misd01/hw08/index.html, www/misd01/hw08/main.js
Odevzdávám úkol č. 8  https://eso.vse.cz/~misd01/cv08/
=> misd01-hw08

www/doho01/hw08/homework.js, www/doho01/hw08/index.html, www/doho01/hw08/style.css
Odevzdávám domácí úkol č.8: https://eso.vse.cz/~doho01/cv08/
=> doho01-hw08

www/velv04/hw08/homework.js, www/velv04/hw08/index.html
Odevzdávám domácí úkol č.8 - https://eso.vse.cz/~velv04/hw08/
=> velv04-hw08

www/urvo00/hw09/css/main.css, www/urvo00/hw09/index.html, www/urvo00/hw09/js/main.js
Dobrý den, odevzdávám hw09:
[https://eso.vse.cz/~urvo00/cv09/homework/](https://eso.vse.cz/~urvo00/cv09/homework/)
=> urvo00-hw09

www/sesm00/hw09/assets/css/style.css, www/sesm00/hw09/assets/js/app.js, www/sesm00/hw09/index.html
Odevzdávám domácí úkol č.9
[https://eso.vse.cz/~sesm00/cv09/homework/](https://eso.vse.cz/~sesm00/cv09/homework/)
=> sesm00 - HW09

www/vitl03/cv09/homework/css/main.css, www/vitl03/cv09/homework/deshift/index.html, www/vitl03/cv09/homework/index.html, www/vitl03/cv09/homework/js/main.js, www/vitl03/cv09/homework/js/second.js, www/vitl03/cv09/homework/shift/index.html
Dobrý den,
odevzdávám úkol 09. 
Dostupný z https://eso.vse.cz/~vitl03/cv09/homework/
Hezký den,
Lukáš Vít, vitl03
=> vitl03-hw09

www/matj27/hw09/css/main.css, www/matj27/hw09/index.html, www/matj27/hw09/js/main.js
Dobrý den,
odevzdávám 9. domácí úkol.
Děkuji,
Matějka
=> matj27-hw09

www/maka09/hw09/index.html, www/maka09/hw09/main.js, www/maka09/hw09/styles.css
Dobrý večer,
odevzdávám DÚ 9 
https://eso.vse.cz/~maka09/cv09
=> maka09-hw09

www/vlav04/hw08/index.html, www/vlav04/hw08/skript.js
Odezdávám domací úkol č.8 https://eso.vse.cz/~vlav04/cv08/
=> vlav04-hw08

www/kosr04/hw08/index.html, www/kosr04/hw08/script.js
Dobrý večer, odevzdávám úkol č. 8
https://eso.vse.cz/~kosr04/hw08/
=> kosr04-hw08

www/mikt04/hw09/css/main.css, www/mikt04/hw09/index.html, www/mikt04/hw09/js/main.js
Dobrý den, odevzdávám úkol cv09 - https://eso.vse.cz/~mikt04/cv09/index.html
Nechal jsem v JS pomocné výpočty a komentáře. Jsem si vědom, že by to šlo na mnoha místech ještě zjednodušit, ale už bych se v tom trochu ztrácel.
Tomáš Mikulenka.
=> mikt04-hw09

www/stom19/hw9/css/main.css, www/stom19/hw9/index.html, www/stom19/hw9/js/main.js
Dobrý den,  odevzdávám dú č.9:  https://eso.vse.cz/~stom19/cv09/index.html
=> stom19-hw9

www/rolt01/hw09/css/main.css, www/rolt01/hw09/index.html, www/rolt01/hw09/js/main.js
Odevzdávám domácí úkol hw09 
https://eso.vse.cz/~rolt01/cv09/homework/
=> rolt01-hw09

www/trat16/hw09/css/main.css, www/trat16/hw09/index.html, www/trat16/hw09/js/main.js
Odevzdávám domácí úkol č.9 
https://eso.vse.cz/~trat16/hw09/
=> trat16-hw09

www/bukp00/hw09/css/main.css, www/bukp00/hw09/index.html, www/bukp00/hw09/js/main.js
Odevzdávám domácí úkol č.9 https://eso.vse.cz/~bukp00/cv09/
=> bukp00-hw09

www/vlav04/hw09/index.html, www/vlav04/hw09/script.js, www/vlav04/hw09/style.css
https://eso.vse.cz/~vlav04/cv09/homework/
=> vlav04-hw09

www/nejj02/hw09/index.html, www/nejj02/hw09/main.css, www/nejj02/hw09/main.js
Dobrý večer,
odevzdávám hw09 dostupný zde: https://eso.vse.cz/~nejj02/hw09/
=> nejj02-hw09

www/sirm02/hw09/css/main.css, www/sirm02/hw09/index.html, www/sirm02/hw09/js/main.js
Odevzdávám úkol č.9  [https://eso.vse.cz/~sirm02/cv09/homework/](https://eso.vse.cz/~sirm02/cv09/homework/)
=> sirm02-hw09

www/legv02/hw09/css/main.css, www/legv02/hw09/index.html, www/legv02/hw09/js/main.js
Odevzdávám domácí úkol cv09:
https://eso.vse.cz/~legv02/cv09/homework/
Vojtěch Legler
=> legv02-hw09

www/kouj10/hw09/css/main.css, www/kouj10/hw09/index.html, www/kouj10/hw09/js/main.js
Odevzdávám domácí úkol č. 9. Odkaz: [https://eso.vse.cz/~kouj10/cv09/](https://eso.vse.cz/~kouj10/cv09/).
=> kouj10-hw09

www/slaj26/hw09/css/main.css, www/slaj26/hw09/index.html, www/slaj26/hw09/js/main.js
Odevzdávám HW 09
https://eso.vse.cz/~slaj26/cv09/
=> slaj26-hw09

www/bake01/hw10/css/main.css, www/bake01/hw10/index.html, www/bake01/hw10/js/main.js
Dobrý den, odevzdávám 10. úkol:
https://eso.vse.cz/~bake01/cv10/homework/
=> bake01-hw10

www/doho01/hw10/homework/css/main.css, www/doho01/hw10/homework/index.html, www/doho01/hw10/homework/js/main.js
Dobrý den, přikládám odkaz na další úkol (hw10):
https://eso.vse.cz/~doho01/cv10/homework/
Děkuji.
=> doho01-hw10

www/doho01/hw09/homework/css/main.css, www/doho01/hw09/homework/index.html, www/doho01/hw09/homework/js/main.js
Dobrý den, odevzdávám svůj zapomenutý úkol (hw09):
https://eso.vse.cz/~doho01/cv09/homework/
Děkuji.
=> doho01-hw09

www/kolj20/hw10/css/main.css, www/kolj20/hw10/index.html, www/kolj20/hw10/js/main.js
Dobrý deň, úkol č. 10:
https://eso.vse.cz/~kolj20/hw10/index.html
=> kolj20-hw10

www/vitl03/cv10/homework/css/main.css, www/vitl03/cv10/homework/index.html, www/vitl03/cv10/homework/js/main.js
Dobrý den,
odevzdávám úkol z 10. cvičení.
https://eso.vse.cz/~vitl03/cv10/homework/
Hezký den,
Lukáš Vít, vitl03
=> vitl03-hw10

www/stom19/hw10/css/main.css, www/stom19/hw10/index.html, www/stom19/hw10/js/script.js
Posílám 10 domácí úkol: https://eso.vse.cz/~stom19/cv10/
=> stom19-hw10

www/kosr04/hw10/css/main.css, www/kosr04/hw10/index.html, www/kosr04/hw10/js/main.js
Dobrý večer,
odevzdávám úkol č. 10
https://eso.vse.cz/~kosr04/cv10/homework
=> kosr04-hw10

www/kunm05/hw10/index.html, www/kunm05/hw10/pexeso.css, www/kunm05/hw10/pexeso.js
https://eso.vse.cz/~kunm05/cv10/homework/
=> kunm05-hw10

www/legv02/hw10/css/main.css, www/legv02/hw10/index.html, www/legv02/hw10/js/main.js
Odevzdávám domácí úkol hw10:
https://eso.vse.cz/~legv02/cv10/homework/
Vojtěch Legler
=> legv02-hw10

www/rolt01/hw10/css/main.css, www/rolt01/hw10/index.html, www/rolt01/hw10/js/main.js
Odevzdávám domácí úkol č. 10 
https://eso.vse.cz/~rolt01/cv10/homework/
=> rolt01-hw10

www/urvo00/hw10/css/main.css, www/urvo00/hw10/index.html, www/urvo00/hw10/js/main.js
Dobrý den, odevzdávám úkol č. 10:
[https://eso.vse.cz/~urvo00/cv10/homework/](https://eso.vse.cz/~urvo00/cv10/homework/)
=> urvo00-hw10

www/bukp00/hw10/css/main.css, www/bukp00/hw10/homework/index.html, www/bukp00/hw10/js/main.js
Odevzdávám domácí úkol č.10: https://eso.vse.cz/~bukp00/cv10/homework/
=> bukp00-hw10

www/sesm00/hw10/css/main.css, www/sesm00/hw10/index.html, www/sesm00/hw10/js/main.js
Odevzdávám domácí úkol č.10
[https://eso.vse.cz/~sesm00/cv10/homework/](https://eso.vse.cz/~sesm00/cv10/homework/)
=> sesm00 - HW10

www/orad01/cv09/homework/css/main.css, www/orad01/cv09/homework/index.html, www/orad01/cv09/homework/js/main.js
=> orad01-hw09

www/jocv00/hw10/css/main.css, www/jocv00/hw10/index.html, www/jocv00/hw10/js/main.js
Odevzdávám úkol č.10: https://eso.vse.cz/~jocv00/cv10/homework/
=> jocv00-hw10

www/kouj10/hw10/css/main.css, www/kouj10/hw10/index.html, www/kouj10/hw10/js/main.js
Odevzdávám dú číslo 10. Odkaz: [https://eso.vse.cz/~kouj10/cv10/](https://eso.vse.cz/~kouj10/cv10/)
Nenahrávám obrázky, ale kdyby byly potřeba, dodám.
=> kouj10-hw10

www/matj27/hw10/css/main.css, www/matj27/hw10/index.html, www/matj27/hw10/js/main.js
Dobrý den,
odevzdávám 10. domácí úkol
Děkuji, Matějka
https://eso.vse.cz/~matj27/hw10/
https://eso.vse.cz/~matj27/hw10/js/main.js
https://eso.vse.cz/~matj27/hw10/css/main.css
=> matj27-hw10

www/fras07/cv10/css/style.css, www/fras07/cv10/index.html, www/fras07/cv10/js/main.js
Dobrý den, 
omlouvám se, že odevzdávám úkol se zpožděním.
https://eso.vse.cz/~fras07/www/fras07/cv10/
Frajtová
=> fras07-hw10

www/vlav04/hw10/css/main.css, www/vlav04/hw10/index.html, www/vlav04/hw10/js/main.js
Dobrý den,
omlouvám se, že odevzdávám úkol se zpožděním.
https://eso.vse.cz/~vlav04/cv10/
=> vlav04-hw10

www/urvo00/hw12/css/main.css, www/urvo00/hw12/index.html, www/urvo00/hw12/js/main.js
Dobrý den, odevzdávám úkol z cv. 12:
[https://eso.vse.cz/~urvo00/cv12/homework/](https://eso.vse.cz/~urvo00/cv12/homework/)
=> urvo00-hw12

www/jocv00/hw12/css/main.css, www/jocv00/hw12/index.html, www/jocv00/hw12/js/main.js
Odevzdávám úkol č.12: https://eso.vse.cz/~jocv00/cv12/homework/
=> jocv00-hw12

www/vitl03/cv12/homework/css/main.css, www/vitl03/cv12/homework/index.html, www/vitl03/cv12/homework/js/app.js
Dobrý den,
odevzdávám úkol č. 12. 
Dostupné na: https://eso.vse.cz/~vitl03/cv12/homework/
Přeji hezký den,
Lukáš Vít, vitl03
=> vitl03-hw12

www/immm00/hw12/index.html, www/immm00/hw12/main.css, www/immm00/hw12/main.js
https://eso.vse.cz/~immm00/cv12/homework/
https://eso.vse.cz/~immm00/cv12/homework/main.js
https://eso.vse.cz/~immm00/cv12/homework/main.css
=> immm00-hw12

www/bukp00/hw12/css/main.css, www/bukp00/hw12/homework/index.html, www/bukp00/hw12/js/main.js
Odevzdávám domací úkol č.12: https://eso.vse.cz/~bukp00/cv12/homework/
=> bukp00-hw12

www/sesm00/hw12/css/main.css, www/sesm00/hw12/index.html, www/sesm00/hw12/js/main.js
Odevzdávám domácí úkol č.10
[https://eso.vse.cz/~sesm00/cv12/homework/](https://eso.vse.cz/~sesm00/cv12/homework/)
=> sesm00-hw12

www/kolj20/hw12/css/main.css, www/kolj20/hw12/index.html, www/kolj20/hw12/js/app.js
Dobrý den, odevzdávam opravenou [verzi](https://eso.vse.cz/~kolj20/hw12/index.html) s opravenou strukturou složek.
=> kolj20-hw12

www/doho01/hw12/css/main.css, www/doho01/hw12/index.html, www/doho01/hw12/js/main.js
Dobrý večer, odevzdávám svůj zapomenutý úkol (domácí úkol č.12).
Odkaz je zde: https://eso.vse.cz/~doho01/cv12/homework/
=> doho01-hw12

www/rolt01/sp2/css/main.css, www/rolt01/sp2/index.html, www/rolt01/sp2/js/granim.js, www/rolt01/sp2/js/main.js
Link na aplikaci sp2 
https://eso.vse.cz/~rolt01/sp2/
=> rolt01-SP2

www/sirm02/sp2/css/main.css, www/sirm02/sp2/index.html, www/sirm02/sp2/js/main.js
link na eso: [https://eso.vse.cz/~sirm02/sp2/](https://eso.vse.cz/~sirm02/sp2/)
=> sirm02-sp2

www/kunm05/sp2/index.html, www/kunm05/sp2/main.js, www/kunm05/sp2/style.css
https://eso.vse.cz/~kunm05/sp2/
Hotový Javascript i CSS a html.
U odevzdávání zadání jsem zapomněla pojmenovat branch, tak vytvářím novou se správným jménem.
=> kunm05-sp2

www/nejj02/sp2/assets/css/main.css, www/nejj02/sp2/assets/js/main.js, www/nejj02/sp2/assets/main.css, www/nejj02/sp2/assets/main.js, www/nejj02/sp2/index.html
https://eso.vse.cz/~nejj02/sp2/
=> nejj02-sp2

www/kouj10/sp2/index.html, www/kouj10/sp2/js/main.js, www/kouj10/sp2/styles/main.css
Link to application: [https://eso.vse.cz/~kouj10/sp2/](https://eso.vse.cz/~kouj10/sp2/)
=> kouj10-sp2

www/vesl05/sp2/css/style.css, www/vesl05/sp2/index.html, www/vesl05/sp2/js/app.js, www/vesl05/sp2/js/googleAPI.js
Odkaz na pilotní verzi aplikace - https://eso.vse.cz/~vesl05/sp2/
=> vesl05-sp2

www/vlav04/sp2/assets/css/style.css, www/vlav04/sp2/assets/js/skript.js, www/vlav04/sp2/index.html
https://eso.vse.cz/~vlav04/sp2/index.html
=> vlav04-sp2

assets/css/style.css, assets/scripts/email-checker.js, assets/scripts/email-client.js, assets/scripts/init.js, assets/scripts/main.js, index.html, www/fort02/sp2/assets/css/style.css, www/fort02/sp2/assets/scripts/email-checker.js, www/fort02/sp2/assets/scripts/email-client.js, www/fort02/sp2/assets/scripts/init.js, www/fort02/sp2/assets/scripts/main.js, www/fort02/sp2/index.html
Odkaz na pilotní verzi: https://eso.vse.cz/~fort02/sp2/
Do finální verze přidám možnost číst přijaté, aby šlo odpovědět.
=> fort02-sp2

www/novo09/sp2/assets/css/main.css, www/novo09/sp2/assets/js/main.js, www/novo09/sp2/index.html
Link to application: https://eso.vse.cz/~novo09/sp2/
=> novo09-sp2

www/trat16/sp2/assets/main.js, www/trat16/sp2/assets/style.css, www/trat16/sp2/index.html
SP2 https://eso.vse.cz/~trat16/sp2/
=> trat16-sp2

www/KONS04/sp2/app.js, www/KONS04/sp2/index.html, www/KONS04/sp2/main.css
Odkaz na aplikaci: https://eso.vse.cz/~kons04/sp2/
=> kons04 - sp2

CSS/styles.css, JS/script.js, index.html, www/maka09/sp2/CSS/styles.css, www/maka09/sp2/JS/script.js, www/maka09/sp2/index.html
odevzdání pilotní verze sp2 
https://eso.vse.cz/~maka09/sp2/
=> maka09-sp2
